server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            exposedHeaders:
              - Authorization
            maxAge: 3600
      discovery:
        locator:
          enabled: true 
      routes:
        - id: user-service-route
          uri: lb://USER-SERVICE 
          predicates:
            - Path=/api/auth/**
          filters:
            - AuthenticationFilter

        - id: task-service-route
          uri: lb://TASK-SERVICE
          predicates:
            - Path=/api/tasks/**
          filters:
            - AuthenticationFilter

jwt:
  secret: "your-256-bit-secret-key-here123456789012345678901234567890"
  expiration.ms: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"