server:
  port: 8080
  ssl:
    enabled: true
    key-store: ${SSL_KEYSTORE_PATH}
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12

spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
        max-retries-on-same-service-instance: 3
        max-retries-on-next-service-instance: 2
        retry-on-all-operations: true
    gateway:
      httpclient:
        pool:
          max-connections: 1000
          acquire-timeout: 5000
          max-idle-time: 60000
      httpserver:
        wiretap: false
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
        max-wait: -1ms

# 生產環境的 Eureka 配置
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URLS:http://prod-eureka-1:8761/eureka/,http://prod-eureka-2:8762/eureka/}
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    secure-port-enabled: true
    secure-port: ${server.port}
    non-secure-port-enabled: false

# 生產環境安全配置
app:
  security:
    jwt:
      secret: ${JWT_SECRET}
      # 12小時
      expiration: 43200000  

# 生產環境日誌配置
logging:
  level:
    root: WARN
    '[com.example.gateway]': WARN
    '[org.springframework.cloud.gateway]': WARN
    '[org.springframework.security]': WARN
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    path: /var/log/gateway-service/
    name: gateway.log
    max-size: 10MB
    max-history: 30

# 監控配置
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  health:
    circuitbreakers:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  file:
    name: /var/log/gateway-service/gateway.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
