server:
  port: 8080

spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
        max-retries-on-same-service-instance: 2
        max-retries-on-next-service-instance: 1
        retry-on-all-operations: true

# 測試環境的 Eureka 配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://test-eureka:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 20
    lease-expiration-duration-in-seconds: 60

# 測試環境安全配置
jwt:
  secret: ${JWT_SECRET:testSecretKey123456789}
  expiration: 86400000  # 24小時

# 測試環境日誌配置
logging:
  level:
    root: INFO
    '[com.example.gateway]': INFO
    '[org.springframework.cloud.gateway]': INFO
    '[org.springframework.security]': INFO

# 測試環境監控配置
management:
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    tags:
      environment: test
