server:
  port: 8080

logging:
  level:
    root: INFO
    "[com.example.gateway]": DEBUG
    "[com.example.gateway.filter.AuthenticationFilter]": DEBUG
    "[org.springframework.cloud.gateway]": DEBUG
    "[org.springframework.security]": DEBUG
    "[org.springframework.web]": DEBUG
    "[org.springframework.cloud.gateway.route]": TRACE
    "[org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping]": DEBUG
    "[org.springframework.cloud.gateway.filter.factory]": DEBUG
    "[org.springframework.cloud.netflix.eureka]": DEBUG

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway-service

  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      default-filters:
        - name: DedupeResponseHeader
          args:
            name: Access-Control-Allow-Origin
            strategy: RETAIN_FIRST
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
      routes:
        - id: user-service-auth-route
          uri: lb://USER-SERVICE
          order: 0
          predicates:
            - Path=/api/auth/login
          filters:
            - name: DedupeResponseHeader
              args:
                name: Access-Control-Allow-Origin
                strategy: RETAIN_FIRST
          metadata:
            connect-timeout: 2000
            response-timeout: 5000

        - id: user-service-route
          uri: lb://USER-SERVICE
          order: 1
          predicates:
            - Path=/api/auth/**
          filters:
            - name: AuthenticationFilter
          metadata:
            connect-timeout: 2000
            response-timeout: 5000

        - id: task-service-route
          uri: lb://TASK-SERVICE
          order: 2
          predicates:
            - Path=/api/tasks/**
          filters:
            - name: AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: taskServiceCircuitBreaker
                fallbackUri: forward:/fallback
          metadata:
            connect-timeout: 2000
            response-timeout: 5000

jwt:
  secret: "your-super-secret-key-that-should-be-in-env-vars-and-much-longer"
  expiration.ms: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  hystrix:
    enabled: true
  circuitbreaker:
    enabled: true
