server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/api/auth/**]':
            allowedOrigins:
              - "http://127.0.0.1:5500"
              - "http://localhost:5500"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
            allowedHeaders:
              - Content-Type
              - Authorization
            exposedHeaders:
              - Authorization
            allowCredentials: false
            maxAge: 3600
          '[/**]':
            allowedOrigins:
              - "http://127.0.0.1:5500"
              - "http://localhost:5500"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            exposedHeaders:
              - Authorization
              - X-Total-Count
            allowCredentials: false
            maxAge: 3600
      discovery:
        locator:
          enabled: true 
      routes:
        - id: user-service-route
          uri: lb://USER-SERVICE 
          predicates:
            - Path=/api/auth/**
          filters:
            - AuthenticationFilter

        - id: task-service-route
          uri: lb://TASK-SERVICE
          predicates:
            - Path=/api/tasks/**
          filters:
            - AuthenticationFilter

jwt:
  secret: "your-256-bit-secret-key-here123456789012345678901234567890"
  expiration.ms: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG