server:
  port: 8080

spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true

# 開發環境的 Eureka 配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

# 開發環境安全配置
security:
  jwt:
    secret: devSecretKey123456789
    # 24小時
    expiration: 86400000  

# 開發環境日誌配置
logging:
  level:
    root: INFO
    '[com.example.gateway]': DEBUG
    '[org.springframework.cloud.gateway]': DEBUG
    '[org.springframework.security]': DEBUG
    '[org.springframework.web]': DEBUG
    '[org.springframework.http]': DEBUG

# 開發環境監控配置
management:
  endpoint:
    health:
      show-details: always
